### fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

###create a new task
POST http://localhost:3200/tasks
Content-Type: application/json
{
    "title": "hello world",
    "date": "2023-02-14 12:00:00",
    "description": "hello world description again",
    "priority": "normal",
    "status": "todo"
}

###update a new task
PUT http://localhost:3200/tasks
Content-Type: application/json
{
    "id" : "3cb3c635-ac6f-11ed-b2ce-1002b54d59da",
    "status": "inProgress"
}